import Footer from './components/Footer';
import Nav from './components/Nav';
import TopHeader from './components/TopHeader';
import './globals.css';
import { Sora} from 'next/font/google';

const sora = Sora ({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});



export const metadata = {
  title: 'Design Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${sora.className}`}>
    <Nav /> 
    <TopHeader />     
    <div>{children}</div>
    <Footer />
    </body>
  </html>
  )
}
